<?php
namespace App\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ActivityRepository;
use App\Repository\CategoryRepository;
use App\Entity\Activity;
use App\Entity\Category;
use App\Entity\Picture;
use App\Form\CommentType;
use App\Form\ActivityType;
use App\Form\PictureType;
use App\Entity\Comment;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use App\Repository\CommentRepository;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
class ActivityController extends AbstractController
{
     /**
     * @Route("/", name="home")
     */
    public function home(ActivityRepository $repo, CategoryRepository $repoCat)
    {
        $activities = $repo->findAll();
        $categories = $repoCat->findAll();
        return $this->render('home.html.twig', [
            'activities' => $activities,
            'categories' => $categories
        ]);
    }

      /**
     * @Route("/activity/{id}", name="show_activity")
     */
    public function show_activity(Activity $activity,Request $request, ObjectManager $manager)
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           $comment->setActivity($activity);
           $comment->setCreatedAt(new \DateTime());
           $comment->setDeleted(0);
           $manager->persist($comment);
           $manager->flush();

        return $this->redirectToRoute('show_activity', ['id' => $activity->getId()]);
        }

        return $this->render('activity/show.html.twig', [
            'formComment' => $form->createView(),
            'activity' => $activity
        ]);
    }

    /**
     * @Route("/create_activity", name="create_activity")
     */
    public function create_activity(Request $request, ObjectManager $manager){

        $activity = new Activity();
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pictures = $activity->getPictures();
            
            if($pictures){
                foreach ($pictures as $picture ) {
                   $file = $picture->getUrl();
                   $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
                   // Move the file to the directory where brochures are stored
                        try {
                            $file->move(
                                $this->getParameter('pictures_directory'),
                                $fileName
                            );
                        } catch (FileException $e) {
                            // ... handle exception if something happens during file upload
                        }
                        $picture->setUrl($fileName);
                }
            }
            
           $activity->setCreatedAt(new \DateTime());
           $activity->setDeleted(0);
           $manager->persist($activity);
           $manager->flush();

        return $this->redirectToRoute('show_activity', ['id' => $activity->getId()]);
        }

        return $this->render('activity/create_activity.html.twig', [
            'formActivity' => $form->createView(),
            'activity' => $activity
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}